#!/bin/sh

cd /opt/hadoop/payit/

date > /opt/logs/py_hadoop.log

echo $* >> /opt/logs/py_hadoop.log

sudo python py_payout.py $* >> /opt/logs/py_hadoop.log 2>&1
status_code=$?
echo '::'$status_code
if [ ${status_code} != '0' ]
then
    exit $status_code
fi

sudo python py_hdfsReader.py $* >> /opt/logs/py_hadoop.log 2>&1
echo '::'$?

echo $* >> /opt/logs/py_hadoop.log


